name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  verify-project-structure:
    name: Verify project structure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 19
          distribution: 'zulu'

      - name: Verify challenges structure (Konsist)
        run: ./gradlew konsistTest

      - name: spotless check
        run: ./gradlew spotlessCheck

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: konsist-test-report
          path: ./build/reports/tests/konsistTest/

  check-solutions:
    name: Check solutions
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 19
          distribution: 'zulu'

      - name: Generate tests for every solution
        run: ./gradlew generateTests

      - name: Run generated solution tests
        run: ./gradlew test --tests "generated.com.igorwojda.*"

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: solution-test-report
          path: ./build/reports/tests/test/
