name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  verify-project-structure:
    name: Verify project structure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Set up Gradle
        uses: ./.github/actions/setup-gradle

      - name: Verify challenges structure (Konsist)
        run: ./gradlew konsistTest

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: konsist-test-report
          path: ./build/reports/tests/konsistTest/

  spotless-check:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Set up Gradle
        uses: ./.github/actions/setup-gradle

      - name: spotless check
        run: ./gradlew spotlessCheck

  check-solutions:
    name: Check solutions
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Set up Gradle
        uses: ./.github/actions/setup-gradle

      - name: Generate tests for every solution
        run: ./gradlew generateTests

      - name: Run generated solution tests
        run: ./gradlew test --tests "generated.com.igorwojda.*"

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: solution-test-report
          path: ./build/reports/tests/test/

  long-running-check:
    name: Long running check (30 min)
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Sleep 30 min
        run: sleep 1800
